### ISSUE TITLE
Unable to use all examples

### ISSUE THREAD

**Issue by LiuXianBang** [cyberbotics/webots_ros2#910] opened 2024-03-12 07:03 UTC
**Describe the Bug**
Unable to use all examples to slam or nav,including TurtleBot3 E-puck and so on. 

here is the node graph
![微信图片_20240312145726](https://github.com/cyberbotics/webots_ros2/assets/13533545/e920afb5-7102-47df-a40c-caf2a72053ab)

noticed the topic /scan and /imu didn't been subscribe yet,but i already use ros2 launch webots_ros2_turtlebot robot_launch.py slam:=true

here is the console log
![微信图片_20240312145253](https://github.com/cyberbotics/webots_ros2/assets/13533545/f00ed550-6358-4f5a-8fb7-edc6b00158ce)
maybe the wrong in here but i cant find the way to fix this
![微信图片_20240312145350](https://github.com/cyberbotics/webots_ros2/assets/13533545/07712e4a-eaba-4dff-ae2d-69dfc9de3fbe)
 
my english is poor,hope to receive your help

**Comment by wilhem** [comment] 2024-03-18 09:01
It is correlated to this bug [here](https://github.com/cyberbotics/webots_ros2/issues/893).
Despite the fact, that Cyberbotics found allegedly a fix for that bug (which is caused by ros control package), the fix is still not be available yet.
In other words: we need to hope that Cyberbotics release an update soon.

**Comment by LiuXianBang** [comment] 2024-03-22 11:15
thank for comment，but this fix still not working for me :cry

**Comment by wilhem** [comment] 2024-03-22 13:42
Because the package has been updated yet.
Still waiting for the new release....

**Comment by YoungRicky7** [comment] 2024-04-07 07:45
Is it fixed now?

**Comment by wilhem** [comment] 2024-04-07 08:07
Sadly not. Or better. the bug has been fixed, but @Yadunund or Cyberbotics in general didn't release the change though the repository.
Hopefully it will come soon

**Comment by LiuXianBang** [comment] 2024-04-07 08:32
Maybe they forgot they haven't released the new version yet，anyway to communicate  with them easily？

**Comment by YoungRicky7** [comment] 2024-04-07 08:56
> Maybe they forgot they haven't released the new version yet，anyway to communicate with them easily？

Nah, as for me I give up using WEBOTS, I use ignition gazebo as the substitute.

**Comment by skpawar1305** [comment] 2024-04-07 09:52
[ros-humble-webots-ros2-control_2023.1.1-0jammy_amd64.zip](https://github.com/cyberbotics/webots_ros2/files/14896695/ros-humble-webots-ros2-control_2023.1.1-0jammy_amd64.zip)

you can extract n install this
I've compiled it n there's no fishy thing in it 👻

**Comment by wilhem** [comment] 2024-04-07 10:27
Thanks @skpawar1305 but there are some problems because of the fact, that you are not part of cyberbotics.
Not everyone here is just a private person. Some people need an official version from cyberbotics.
By the way, your packages is for jammy only. But many of us use still "humble"

**Comment by skpawar1305** [comment] 2024-04-07 10:34
> Thanks @skpawar1305 but there are some problems because of the fact, that you are not part of cyberbotics. Not everyone here is just a private person. Some people need an official version from cyberbotics. By the way, your packages is for jammy only. But many of us use still "humble"

yes, I had shared it with a student who had build errors. n it's for humble

**Comment by omichel** [comment] 2024-04-08 06:50
I personally don't have the bandwidth to make this release now, but I am happy to help any volunteer to proceed with the release. The release procedure is explained [here](https://github.com/cyberbotics/webots_ros2/wiki/Internal-Publishing) and a PR for preparing the release is already open in #839. Just let me know.

**Comment by wilhem** [comment] 2024-04-08 08:25
@skpawar1305 can you prepare a release for everybody based on your package?

**Comment by skpawar1305** [comment] 2024-04-08 11:07
> @skpawar1305 can you prepare a release for everybody based on your package?

not this week, next week I can 👍

**Comment by omichel** [comment] 2024-04-08 15:57
I found some time this afternoon to proceed with the release. So, now we need to wait for the approval from the ROS 2 maintainers of these 3 PRs:
- [rolling](https://github.com/ros/rosdistro/pull/40507)
- [humble](https://github.com/ros/rosdistro/pull/40509)
- [iron](https://github.com/ros/rosdistro/pull/40510)
Then, the corresponding packages will be published at the next sync.

**Comment by omichel** [comment] 2024-04-09 07:53
**Update**: all the 3 PRs were merged. We are now waiting for the next sync which should happen within a couple of weeks or so on the different distros:

- [rolling](http://repo.ros2.org/status_page/ros_rolling_default.html?q=SYNC)
- [humble](http://repo.ros2.org/status_page/ros_humble_default.html?q=SYNC)
- [iron](http://repo.ros2.org/status_page/ros_iron_default.html?q=SYNC)

**Comment by VincentDelort** [comment] 2024-05-07 13:44
Hi @omichel , when do you believe the fixes will be merged into public (`apt`) version of ros humble (I do not know how to interpret the pages that you linked)?

**Comment by omichel** [comment] 2024-05-07 17:50
It should be already released now. See https://discourse.ros.org/t/new-packages-for-humble-hawksbill-2024-04-18/37272

**Closed by omichel** 2024-05-07 17:50 UTC
